const mongoose=require('mongoose');
const plm=require('passport-local-mongoose')
mongoose.connect('mongodb://127.0.0.1:27017/instaclonedata')
const userSchema=mongoose.Schema({
    username:String,
    name:String,
    followers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'user'
        }
    ],
    followings:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'user'
        }
    ],
    posts:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'post'
        }
    ],
    stories:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'story'
        }
    ],
    messages:[
        {
            type:Array,
            default:[]
        }
    ],
    profilepicture:{
        type:String,
        default:'default.jpg',
    },
    saved:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user',
    }],
    bio:String,
    password:String,
    email:String,

})
userSchema.plugin(plm)
module.exports=mongoose.model('user',userSchema);